### ISSUE TITLE
Doesn't work anymore.

### ISSUE THREAD

**Issue by zetaloop** [danthekidd/Expressive-Animator-Crack#1]
This crack is patched. It doesn't work anymore.

Now it requires a valid lk to pass the verification. It can be an expired one; just need to modify the current time.

**Comment by danthekidd** [comment]
thank you for your feedback. this has been patched and i am working on a new version. the lk is just fine, i just need a new way to bypass the signature. and for v3, i will be making it unpatchable by directly modifying the code of the script to not protect the function.

**Comment by danthekidd** [comment]
V3 is out! it should now work for you 😁

**Comment by danthekidd** [comment]
also check out the 2 other methods I published, one might suit you more than the Userscript

**Comment by artdecooutdoor** [comment]
This crack is patched. It doesn't work anymore.
